version: "3"

services: 
    deliveroo:
        container_name: strapi_deliveroo
        build: .
        restart: unless-stopped
        env_file: .env
        environment: 
            DATABASE_CLIENT: ${DATABASE_CLIENT}
            DATABASE_NAME: ${DATABASE_NAME}
            DATABASE_HOST: ${DATABASE_HOST}
            DATABASE_PORT: ${DATABASE_PORT}
            DATABASE_USERNAME: ${DATABASE_USERNAME}
            DATABASE_PASSWORD: ${DATABASE_PASSWORD}
        ports: 
            - "1337:1337"
        volumes: 
            - .:/usr/src/app
        # extra_hosts: 
        #     somehost: ip
